version: '3'

services:
        influxdb-service:
                image: 'influxdb:latest'
                container_name: influxdb
                ports:
                        - "8083:8083"
                        - "8086:8086"
                        - "8090:8090"
                env_file:
                        - 'env.influxdb'
                volumes:
                        # sudo mkdir -p /srv/docker/influxdb/data
                        - /srv/docker/influxdb/data:/var/lib/influxdb
                        - /etc/timezone:/etc/timezone:ro
                        - /etc/localtime:/etc/localtime:ro

        grafana-service:
                image: 'grafana/grafana:latest'
                container_name: grafana
                ports:
                        - "3000:3000"
                env_file:
                        - 'env.grafana'
                links:
                        - influxdb-service
                volumes:
                        # Data Persistency
                        # mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
                        - /srv/docker/grafana/data:/var/lib/grafana
                        - /etc/timezone:/etc/timezone:ro
                        - /etc/localtime:/etc/localtime:ro

